name: slp_test

channels:
- pytorch
- conda-forge
- jmcmurray


dependencies:
- python=3.7
- scipy
- matplotlib
- opencv  
- pytorch=1.4.0
- torchvision 
- scikit-image
- visdom
- json
- plotly
- jsonpatch (visdom patch)
- dominate 
- tqdm
- configargparse
- yacs
- jupyter
- scikit-image




# name: mocap
# dependencies:
# - python=2.7
# - theano
